name: Add Git Trailers to PR commits

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  git_trailers:
    name: Add Git Trailers to PR commits
    if: ${{ github.event.review.state == 'approved' }}
    uses: nubificus/vaccel/.github/workflows/add-git-trailers.yml@main
    with:
      plugin: 'scripts'
    secrets: inherit
